### ISSUE TITLE
SQLPerms ranks

### ISSUE THREAD

**Issue by aserversmc** [john01dav/SQLPermsIssues#1]
What did you do to produce the issue and how should it be replicated (details will get your issue fixed faster)?
(I was on a bungeecord server) I first had my rank set to default on a live server. Next, I logged off. Then, I set my rank to VIP through console.

What happened?
Received the message saying rank was changed for me.

What did you expect to happen?
I expected to have VIP once I logged back in.

Is it a cosmetic error (ie. errors in the console that don't seem to effect anything) or is it a full-fledge bug (ie. something bad happens that is noticeable to players)?
Major bug as ranks do not change for players.

Link to a pastebin of a FULL SERVER LOG (start server, demonstrate bug, stop server):
I cannot do it at this time as I have SQLPerms running on a live server. However, through spigot, you said you found the issue and will fix it when you can.

Here is the spigot PM I sent regarding the issue I wrote above:

Hey, I have been using SQLPerms for the past couple of days and it is working smoothly now. However, there is one major issue. If the targeted player in /setrank (name) (rank) is offline, the plugin still says the player's rank was changed but after the player relogs, the player is at their previous rank.

For example, Bob is originally rank VIP. I now type /setrank Bob MVP (this is when Bob is offline). I get the message "Bob's rank has been set to MVP in default". Which means it should be good.

However, when Bob relogs, he should be MVP but in-game he is still VIP rank.

**Comment by john01dav** [comment]
Thanks for the report, I'll go fix this right now.

**Comment by john01dav** [comment]
Fixed in 2.2.3
