### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by IlPicasso** [john01dav/SQLPermsIssues#10]
I wanted to ask 

- Global Rank Permissions (Like Gplayeperms but for ranks)
- An ingame editor of permissions (Add and remove permissions of a group from commands)
- List rank permissions with a commands /perm group (group) 
- Integrate timed permissions

**Comment by john01dav** [comment]
This is all a good idea, I'll see what I can do. Could you perhaps create a separate issue for each though for better organization (ie. I can close each individual issue as each feature is implemented).

**Comment by IlPicasso** [comment]
Sure I can
