### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by NoSkillNewbie** [john01dav/SQLPermsIssues#14]
I am not getting any errors at all in my log. So I have absolutely nothing to trace down. I know it is connecting to MySQL as it is making two tables.... playerperms and sqlperms. Playerperms is completely empty and sqlperms gets filled with UUIDs when someone joins and rank null. Have tried with the default permissions.yml as well as a modified permissions.yml edited so that every rank has a tabcolor as suggested... but that didn't do anything either. So far looking like I wasted $15.

config.yml
general:
  refreshIntervalSeconds: 60
  debugMode: true
  enabledChannels:
  - default
tabListColor:
  enabled: false
  channel: default
mysql:
  host: 127.0.0.1
  port: 3306
  database: sqlperms
  username: sqlperms
  password: SQLPASSWORDHERE

permissions.yml
defaultRank:
  default: guest
ranks:
  guest:
    prefix: '&e[Guest] '
    tabColor: 'e'
    op: false
    permissions:
     - -bukkit.command.plugins
     - -bukkit.command.version
    inheritance: []
  admin:
    prefix: '&c[Admin] '
    op: false
    tabColor: 'e'
    permissions:
     - bukkit.command.plugins
     - bukkit.command.version
    inheritance:
     - guest
  owner:
    prefix: '&4[The Owner] '
    op: true
    tabColor: 'e'
    permissions: []
    inheritance:
     - admin

**Comment by john01dav** [comment]
Please provide the following information:
 - Detailed steps to reproduce the problem, I can't help you if I can't make the problem happen myself in an environment where I can examine it in detail.
- Pastebin or code tags for each YML file you posted. I need to check the indentation and formatting which GitHub removes when code tags aren't used.

**Comment by NoSkillNewbie** [comment]
Detailed steps to reproduce?
1. Stop server.
2. Drop SQL Perms jar into plugins.
3. Start server.
4. Stop server.
5. Modify config.yml to have my SQL username/password and DB.
6. Modify the default permissions.yml to include tabColor: 'e' on every rank because your default one doesn't have it and you told me to do this.
7. Start server
8. Connect to server.
9. Talk in chat see tag as default.
10. Alt tab look at databas.
11. Notice playerperms is COMPLETELY EMPTY no matter what permissions.yml file I use.
12. Notice sqlperms always populates with player UUIDs so it is connecting to SQL database.
13. Look in the logs folder of MC to look for errors. Low and behold there are no errors!
14. Post on forums complaining of how it doesn't work.

Default auto-made by the plugin modified so every rank has tabColor permissions.yml (Doesn't work)
http://pastebin.com/xtwYU01v

Default auto-made by the plugin permissions.yml (Doesn't work)
http://pastebin.com/zCRBbUai

permissions.yml I would like to use(Doesn't work)
http://pastebin.com/WJLQyZCK

config.yml
http://pastebin.com/UW8CtG46

**Comment by john01dav** [comment]
It sounds like you want permissions to synchronize as well as ranks. This is not what SQLPerms does. SQLPerms synchronizes what rank each player has, but every server has different settings for each rank. The playerperms table allows the user to give specific permissions to each player using the /playerperms command.

**Comment by NoSkillNewbie** [comment]
Rank is NULL....

**Comment by NoSkillNewbie** [comment]
http://pastebin.com/uieWqug3


http://pastebin.com/3nd51RqQ

**Comment by Zendrex** [comment]
What I learned after a few tries is that your default rank isnt setup right.

If your using channels, list your channels in both the config and in the perms file under default rank.
This is how mine is setup.
(Ignore the periods, just to stop the bullet points & spacing)

Config File:
enabledChannels:
  .- SkyFactory2
  .- DonorRank

Permissions File:
defaultRank:
.  SkyFactory2: Member
.  DonorRank: Member

ranks:
 # Member Ranks # (custom comment for sorting)
 Member:
.   op: false
.   prefix: '&6&lNULL '
.   permissions:
.   - -bukkit.command.version
.   - -bukkit.command.plugins
.   - -bukkit.command.me
.   - -bukkit.command.kill
.   - -bukkit.command.help
.   inheritance: []

What im trying to say is that you never properly setup the default rank for your channels. Pastebin your ranks and config (remove database info) and I will take a look if you dont get it still.

**Comment by NoSkillNewbie** [comment]
Zendrex's fix got the nulls to stop but pretty much every other plugin is having issues with SQLPerms.... All resulting in a variation of the error below.

1:52:27 PM CONSOLE: java.lang.UnsupportedOperationException: SuperPerms no group permissions.

**Comment by Zendrex** [comment]
Post the entire error and your permissions file please.
(In a pastebin)

**Comment by NoSkillNewbie** [comment]
Working permissions.yml
http://pastebin.com/SU0MsQg1

config.yml
http://pastebin.com/cjvsEHHw

One of many errors from many different plugins... They are all the same. Vault can't get primary group.
http://pastebin.com/rdGqShXG

**Comment by john01dav** [comment]
Vault isn't supported by SQLPerms right now.
