### ISSUE TITLE
Channel Errors

### ISSUE THREAD

**Issue by Zendrex** [john01dav/SQLPermsIssues#15]
Log:
http://hastebin.com/bevipesuyu.rb

Server Version:
Cauldron.x.x.x

Seems that you NEED to have the default channel in the config or you get these errors thrown and everything breaks. Every check also throws errors as well. I was hoping to have my channels as: Ranks, Donors. Ranks having my staff and default groups like member, then Donor to obviously have the donor ranks. Seems that cant be the case.

**Comment by john01dav** [comment]
f8425b56-ef1b-4472-9685-7c058a748400-staff
You have multiple instances of this entry in the table `sqlperms`. You need to remove the extra entries. Additionally, all ranks and channels are case sensitive. Therefore, things will break if you use `Ranks` in one place and `ranks` in another place.

**Comment by Zendrex** [comment]
I deleted the tables, made sure my config was correct (posted below) and still getting the same result.

Log: http://hastebin.com/ifehipequt.avrasm

Config:http://hastebin.com/apihipiwik.sm

NOTE:
This is on a fresh config/database.

**Comment by Zendrex** [comment]
I resolved the issue, seemed to be a ending issue of my database not actually deleting the tables.

Its resolved.
