### ISSUE TITLE
Offline player setrank don't work

### ISSUE THREAD

**Issue by kukubaczek** [john01dav/SQLPermsIssues#19]
If I use a command "setrank randomPlayer vip", and that player is offline he don't receive a rank.

**Comment by john01dav** [comment]
Please include detailed steps to reproduce this issue. When I simply use setrank with an offline player myself, it works. For this reason, I assume you are doing something different.

**Comment by john01dav** [comment]
Closed due to inactivity, feel free to re-open it if you come back.
