### ISSUE TITLE
EzChat Not working

### ISSUE THREAD

**Issue by aerothan** [john01dav/SQLPermsIssues#2]
http://pastebin.com/eU82C7XE

Got my log in the pastebin above, thanks for the help in advance!

[07:46:15] [Server thread/ERROR]: Could not load 'plugins\EzChat.jar' in folder 'plugins'

**Comment by john01dav** [comment]
Try running with Oracle JDK/JRE 7 or OpenJDK 8.

**Comment by john01dav** [comment]
Also, please fix the other errors in your setup (ie. the errors in permissions.yml).

**Comment by john01dav** [comment]
It should be fixed in 1.0.1. Please open a new issue if it turns out not to be fixed.

**Comment by aerothan** [comment]
same issue, http://pastebin.com/fS2vzAs4

**Comment by aerothan** [comment]
and this is on the 1.0.1

**Comment by aerothan** [comment]
Any Updates? Thanks.

**Comment by john01dav** [comment]
The issue is currently in progress of being fixed. If you want me to prove it works for others, send me a PM on Spigot.

**Comment by aerothan** [comment]
Is there a eta for the fix? It might work but doesnt help me if mine isnt working lol

**Comment by aerothan** [comment]
http://pastebin.com/E9wj6nLw

**Comment by john01dav** [comment]
There is no ETA at the current moment.

**Comment by aerothan** [comment]
Any updates would really like to get this working

**Comment by john01dav** [comment]
[I think I found a lead on what's up.](www.spigotmc.org/threads/spigot-premium-resources-changing-jar-files-why.61370) Once this lead solidifies, I'll fix this if this lead is truly what is causing the error. I can see why it would be too.

**Comment by john01dav** [comment]
Ok, I've been talking to md_5 about this, it turns out that Spigot messes with Jar files uploaded and there messing is causing the errors -- which is why it didn't happen in my testing. If someone wants the original Jar file, then please PM me your Spigot email.

**Comment by john01dav** [comment]
md_5 told me that Spigot changed its messing-with algorithm, so it should be fixed now even for those who download from Spigot.
