### ISSUE TITLE
[Important] Factions disabling prefixes.

### ISSUE THREAD

**Issue by DynamicMC** [john01dav/SQLPermsIssues#21]
Factions 2.7.5 the latest version from www.massivecraft.com is interfering with prefixes. Please fix.

:) <3

**Comment by john01dav** [comment]
Thanks for the report. This will be fixed in 3.0 or possibly earlier.

**Comment by slebu** [comment]
I have the same problem.

**Comment by john01dav** [comment]
Fixed in 2.3.0.
