### ISSUE TITLE
Duplicate entry?

### ISSUE THREAD

**Issue by DynamicMC** [john01dav/SQLPermsIssues#23]
Duplicate entry 'e582e287-f609-41b2-98a6-e4d772ad5498-donator' for key 'PRIMARY'
I was testing my groups, and they seem to somehow have duplicated?

**Comment by DynamicMC** [comment]
e.g /setrank dynamicmc_ tier1 donator, and /setrank dynamicmc_ nondonor donator

**Comment by john01dav** [comment]
Could you give the exact steps you used so that I can reproduce the problem?

**Comment by DynamicMC** [comment]
I'm not exactly sure, It was fine at first then I added another channel called donator, I was putting my self in different ranks. At one time I put myself in owner on the channel default and donator. This is the full error http://pastebin.com/EQ6nyuZG spamming continuously.

**Comment by john01dav** [comment]
Everything is case sensitive. Did you use, ie. "Vip" in one place and "vip"
in another?

**Comment by DynamicMC** [comment]
Would playernames be case sensitive too?

**Comment by john01dav** [comment]
Not in theory, but it could be a possibility of what caused the error.

**Comment by DynamicMC** [comment]
Just checked, it was fine for a while. Then the error appeared and I lost the rank. http://gyazo.com/d5c4716f53c604f203576b4b3dfa0418

**Comment by john01dav** [comment]
So it just occurred randomly with no clear cause?

**Comment by DynamicMC** [comment]
No, I just set the rank. Wait for the error and it disapears. This is only for my donator channel, my default channels fine.

**Comment by john01dav** [comment]
Verify that the donator channel has the same case in the following places:
 - config.yml (all servers)
 - database (actually open the database in phpmyadmin)
 - all uses of it in any commands in the logs by any player

**Comment by DynamicMC** [comment]
I'm getting null for MYUUID-donator http://gyazo.com/67b3114e2b2ac7a6427b20b44aba0896

**Comment by john01dav** [comment]
Try dropping that row, then go through each step you used to place that row
there. Check if it's null in between each step and once you find the step
that nulls it, post each step you took before it became null here.

**Comment by DynamicMC** [comment]
After deleting the line I haven't seen this error once! http://gyazo.com/d3ce38df5fecc1cc9d05249e6b6d0dee Thanks! And if it happens again its always an easy fix :P

**Comment by john01dav** [comment]
Ok, I'm glad to know that :). This bug is something that several people
report, but no one has been able to pin down what causes it. Once it is
known why it happens, then it can be fixed.
