### ISSUE TITLE
The Duplicate entry error

### ISSUE THREAD

**Issue by DynamicMC** [john01dav/SQLPermsIssues#26]
It seems to come when I; Join the server, leave the server, add a new channel (donator), and when I join back it doesnt set me to the nondonor group it just goes null and gives me the error

**Comment by john01dav** [comment]
Are you setting a default rank for the new channel on all servers?

**Comment by DynamicMC** [comment]
yes

**Comment by DynamicMC** [comment]
Oh actually, nvm lol. Thats my problem. But I have a new one :D I updated to 2.3.0 and I no longer have access to minecrafts op features.

**Comment by DynamicMC** [comment]
E.g /reload, I can't build in spawn protection, I can't do /minecraft:{command}

**Comment by john01dav** [comment]
1) Please create an issue soley for OP perms, I'm closing your other issues.
2) When you /op yourself manually (SQLPerms should let that happen for at least a few seconds) does everything work?
