### ISSUE TITLE
OP perms

### ISSUE THREAD

**Issue by DynamicMC** [john01dav/SQLPermsIssues#27]
Yes OP perms work for the few seconds, then I lose them. These are only the minecraft commands like /minecraft:say /minecraft:etc and /bukkit:etc.. 
Other commands from plugins like essentials are working fine

**Comment by DynamicMC** [comment]
And now my admin rank, with OP isn't working at all. No console errors at all.

**Comment by john01dav** [comment]
Fixed in 2.3.1
