### ISSUE TITLE
Player can add permissions!

### ISSUE THREAD

**Issue by kukubaczek** [john01dav/SQLPermsIssues#28]
[19:29:41 INFO]: aruturek issued server command: /gplayerperms add kukubaczeek *

THIS IS WORKING WITHOUT PERMISSION!

**Comment by kukubaczek** [comment]
I'm using the latest version

**Comment by DynamicMC** [comment]
Yea I'm getting this too, theres no permission node for gplayerperms

**Comment by DynamicMC** [comment]
for now maybe get a plugin like plsecure and block the command

**Comment by john01dav** [comment]
I is fixed in 2.3.2.
