### ISSUE TITLE
SQLPerms v2.2.1 (Is it up to date?)

### ISSUE THREAD

**Issue by aerothan** [john01dav/SQLPermsIssues#3]
After you rolled back from 2.2.2 my plugin no longer will connect to the database. I have redownloaded the file you sent but same issue.

[Server] ERROR Error occurred while enabling SQLPerms v2.2.1 (Is it up to date?)

**Comment by john01dav** [comment]
Could you post a full log please? I can't tell what is happening without it.

**Comment by aerothan** [comment]
http://pastebin.com/UTzx2wTR

**Comment by john01dav** [comment]
It looks like your database settings are incorrect. Update to 2.2.3 (I just posted it on Spigot) and give me a log with debugMode enabled in config.yml.

**Comment by aerothan** [comment]
doubled checked my DB settings, same settings that I was using before. New pastbin with the 2.2.3

http://pastebin.com/rLrS4MBB

**Comment by john01dav** [comment]
It looks like an iptables or other firewall misconfiguration. Basically, SQLPerms is sending a message to the database and the database confirms receiving the message, but never replies.

**Comment by aerothan** [comment]
Anything you could recommend to fix it?

**Comment by MiamiCat** [comment]
Im getting this error. What do I have to do.
http://pastebin.com/caSWMAUA

**Comment by john01dav** [comment]
@aerothan Reverse any changes you made to the configuration of anything on your phsycial server (or ask your host for a list) since the last time SQLPerms worked for you.

@MiamiCat You should create your own issue instead of hijacking, however all you need to do is update to the latest version (2.2.3).

**Comment by aerothan** [comment]
So i went ahead and swapped out databases, which seem to fix the connection issue. But i got a new issue not sure what it is doing.

http://pastebin.com/h8d9707Z

**Comment by aerothan** [comment]
Any updates to this issue?

**Comment by john01dav** [comment]
Is the server running for more than 8 hours without a player online? If so, it should work, but if it fails to that is what the error you posted means. Try testing for this bug right when the server starts. Also, don't use /reload -- ever.

**Comment by aerothan** [comment]
It does it all day spitting that error and it does do it right after a full restart

**Comment by aerothan** [comment]
Resolved using a local database instead of a external for a quick fix
