### ISSUE TITLE
SQLPerms not working at all

### ISSUE THREAD

**Issue by Nik-AP** [john01dav/SQLPermsIssues#5]
Hello,

I'm having issues with the chat prefix. I'm using the latest SQLPerms version with EssentialsChat as my chat manager. I've entered my chat format as

format: '[sqlpermsprefix-staff] [sqlpermsprefix-default] &r{DISPLAYNAME}&r&7» &r&f{MESSAGE}'

But on my screen I see: http://i.imgur.com/UrlUib7.png

Start up log: http://pastebin.com/ALNE8Wp8
(No errors on talking, disable etc).

It was working fine then I updated essentials and this happened. I didn't change anything at all. So I downgraded essentials and then it still happened.

Please help!

**Comment by john01dav** [comment]
That log is in reverse order, which usually happens when copying/pasting from a Multicraft console. Could you get me a copy from latest.log that will be in the correct order?

**Comment by john01dav** [comment]
I will close this after 5 total days if inactivity. There are 3 days remaining.
