### ISSUE TITLE
SqlTokens Error

### ISSUE THREAD

**Issue by MiamiCat** [john01dav/SQLPermsIssues#6]
Im getting this error on the plugin SqlTokens. Take a look
http://pastebin.com/4Br035ZT

**Comment by john01dav** [comment]
Is the server running for more than 8 hours with no players?

**Comment by MiamiCat** [comment]
Yes...

**Comment by john01dav** [comment]
That is causing the connection to expire. I'll fix it anyway though.

**Comment by MiamiCat** [comment]
So, what do I have to do, erase config.yml??

**Comment by john01dav** [comment]
Get players, or wait for my update.

**Comment by MiamiCat** [comment]
When would be the next update? I would have to close my server until the next update and the this would be fixed, the reason was that I put the server on white-list all the weekend until I came back from vacation I understand now.

**Comment by john01dav** [comment]
It will probably be either today or tommorow. Just have your server restart
every 7 hours until then.

**Comment by john01dav** [comment]
Done
