### ISSUE TITLE
Same issue as before

### ISSUE THREAD

**Issue by aserversmc** [john01dav/SQLPermsIssues#7]
I won't recopy my previous issue. I am running my server on 1.8.3 spigot through an online bungeecord server. My UUIDs match up and the SQLPerms works fine if the player is online. However, if the player is offline and you change his rank, it does not change it when they log on.

**Comment by versiuxP3** [comment]
On my server but use 1.8 Spigot "SQL Tokens" no load jump errors in the console. But not to be!

http://pastebin.com/b14PatGH

**Comment by john01dav** [comment]
Can't reproduce with these steps:
 - Setup Spigot instance in offline mode (using version git-Spigot-bf0ac55-3fc97ff)
 - Install SQLPerms
 - Set server.properties to offline mode
 - Join server, see guest rank
 - Leave server, do /setrank john01dav owner in console
 - Join server, see owner rank

If you are doing something different, please share with equally detailed information.

**Comment by aserversmc** [comment]
I am using version git-Spigot-2f787bd-ea28011

1. Running an offline server.
2. Install SQLPerms, configure ect.
3. Setting my player rank before I join (I did this when I reset my server so all players had rank when they joined, wasn't an issue)
4. In step 3, I would do /setrank aditap1 vip in-game with another account
5. I once aditap1 joined the server as a new player, he got vip from beginning.
6. Aditap1 leaves server
7. Aditap1 purchases rank upgrade. Enjin runs console command, /setrank aditap1 vip+  (Note, aditap1 is offline)
8. Aditap1 joins server but still has vip rank and not vip+

**Comment by john01dav** [comment]
Is it by any chance running through BungeeCord with ip forwarding enabled?

**Comment by john01dav** [comment]
This issue is closed due to inactivity.
