### ISSUE TITLE
Error SkyWarsReloaded

### ISSUE THREAD

**Issue by versiuxP3** [john01dav/SQLPermsIssues#8]
01.05 21:22:33 [Server] INFO ... 14 more
01.05 21:22:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
01.05 21:22:33 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
01.05 21:22:33 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
01.05 21:22:33 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
01.05 21:22:33 [Server] INFO at com.walrusone.skywars.listeners.SignListener.signPlaced(SignListener.java:38) ~[?:?]
01.05 21:22:33 [Server] INFO at com.walrusone.skywars.controllers.GameController.addSignJoinGame(GameController.java:180) ~[?:?]
01.05 21:22:33 [Server] INFO at com.walrusone.skywars.controllers.GameController.createGame(GameController.java:209) ~[?:?]
01.05 21:22:33 [Server] INFO at com.walrusone.skywars.game.Game.<init>(Game.java:126) ~[?:?]
01.05 21:22:33 [Server] INFO at com.walrusone.skywars.game.Game.getGameMap(Game.java:139) ~[?:?]
01.05 21:22:33 [Server] INFO at com.walrusone.skywars.game.GameMap.loadMap(GameMap.java:115) ~[?:?]
01.05 21:22:33 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.api.MultiverseWorld.setDifficulty(Lorg/bukkit/Difficulty;)Z
01.05 21:22:33 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
01.05 21:22:33 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
01.05 21:22:33 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
01.05 21:22:33 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInUpdateSign.a(SourceFile:10) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInUpdateSign.a(SourceFile:43) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1817) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:22:33 [Server] INFO org.bukkit.event.EventException
01.05 21:22:33 [Server] ERROR Could not pass event SignChangeEvent to SkyWarsReloaded v2.1.8
01.05 21:22:33 [Server] INFO Preparing start region for level 2 (Seed: -1024946660393637971)
01.05 21:22:33 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
01.05 21:21:57 [Server] INFO ... 14 more
01.05 21:21:57 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO at com.walrusone.skywars.commands.MainCommand.onCommand(MainCommand.java:75) ~[?:?]
01.05 21:21:57 [Server] INFO at com.walrusone.skywars.commands.JoinGameCommand.onCommand(JoinGameCommand.java:38) ~[?:?]
01.05 21:21:57 [Server] INFO at com.walrusone.skywars.controllers.GameController.findGame(GameController.java:88) ~[?:?]
01.05 21:21:57 [Server] INFO at com.walrusone.skywars.controllers.GameController.createGame(GameController.java:94) ~[?:?]
01.05 21:21:57 [Server] INFO at com.walrusone.skywars.game.Game.&lt;init&gt;(Game.java:126) ~[?:?]
01.05 21:21:57 [Server] INFO at com.walrusone.skywars.game.Game.getGameMap(Game.java:139) ~[?:?]
01.05 21:21:57 [Server] INFO at com.walrusone.skywars.game.GameMap.loadMap(GameMap.java:115) ~[?:?]
01.05 21:21:57 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.api.MultiverseWorld.setDifficulty(Lorg/bukkit/Difficulty;)Z
01.05 21:21:57 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
01.05 21:21:57 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
01.05 21:21:57 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
01.05 21:21:57 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
01.05 21:21:57 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'swr' in plugin SkyWarsReloaded v2.1.8
01.05 21:21:57 [Server] ERROR null

**Comment by john01dav** [comment]
Please explain:
 - How to reproduce the error (be detailed)
 - What you expect to happen
 - What happened
 - Any errors/logs/etc. that could possibly be relevant in any way; make sure they are in pastebin or a similar service so they are properly formatted

**Comment by john01dav** [comment]
This issue is closed due to inactivity.
